version: 2
jobs:
  build_code_develop:
    docker:
      - image: circleci/node:12

    working_directory: ~/rensol-test
    steps:
      - checkout

      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

      - run:
          name: npm install
          command: npm i

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules
      - run:
          name: build
          command: npm run build



  deploy_code_develop:
    docker:
      - image: circleci/node:12
    working_directory: ~/rensol-test
    steps:

      - run:
          name: run
          command: npm run start

  

workflows:
  version: 2
  build_deploy_develop:
     jobs:
      - build_code_develop:
          filters:
            branches:
              only:
                - circle-ci-addition
      - deploy_code_develop:
          filters:
            branches:
              only:
                - circle-ci-addition
          requires:
            - build_code_develop
            


